-- Insert test data for admit card testing
INSERT INTO registrations (
  player_id,
  player_name,
  age,
  category,
  dob,
  gender,
  parent_name,
  phone,
  email,
  address,
  events,
  total_fee,
  payment_status,
  photo_url,
  created_at
) VALUES (
  'LKO2026-TEST',
  'Arjun Kumar',
  12,
  'U-13',
  '2014-05-15',
  'Male',
  'Rajesh Kumar',
  '9876543210',
  'arjun.kumar@example.com',
  '123 Main Street, Lucknow, UP 226001',
  ARRAY['U-13 Boys Singles', 'U-13 Boys Doubles', 'U-15 Boys Singles'],
  2200,
  'paid',
  null,
  now()
) ON CONFLICT (player_id) DO UPDATE SET
  player_name = EXCLUDED.player_name,
  age = EXCLUDED.age,
  category = EXCLUDED.category,
  dob = EXCLUDED.dob,
  gender = EXCLUDED.gender,
  parent_name = EXCLUDED.parent_name,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  address = EXCLUDED.address,
  events = EXCLUDED.events,
  total_fee = EXCLUDED.total_fee,
  payment_status = EXCLUDED.payment_status,
  photo_url = EXCLUDED.photo_url;